<?php

/**
 * @file
 * Contains copyright_block.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function copyright_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the copyright_block module.
    case 'help.page.copyright_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My copyright block') . '</p>';
      return $output;

    default:
  }
}
